In [ ]:
!pip install gensim==4.3
!pip install --upgrade numpy==1.22.0
!pip install datasets
!pip install -U spacy
!python -m spacy download en_core_web_sm
!pip install advertools
!pip install simplemma
!pip install nltk==3.7

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 29.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 KB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20443 sha256=e8d349053587b2ed04fd672fb1a12b430719e1def56e5fce8df27898342b542a
  Stored in directory: /root/.cache/pip/wheels/6a/65/c4/d27eeee9ba3fc150a0dae150519591103b9e0dbffde3ae77dc
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3530 sha256=678c63cf6cb60e8ebad684907643b119a2c616dddb8cdc4caccf99f1a290015e
  Stored in directory: /root/.cache/pip/wheels/ba/d9/a0/ddd93af16d5855dd9bad417623e70948fdac119d1d34fb17c8
Successfully built fst-pso miniful
  Attempting uninstall: gensim
    Found existing installation: gensim 3.6.0
    Uninstalling gensim-3.6.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 19.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 491.4 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 KB 27.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 KB 16.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 14.8 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 28.4 MB/s eta 0:00:00
  Attempting uninstall: spacy
    Found existing installation: spacy 3.4.4
    Uninstalling spacy-3.4.4:
      Successfully uninstalled spacy-3.4.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency confli

In [ ]:
import re
import pandas as pd
from datasets import load_dataset
import pandas as pd
import advertools as adv
import nltk
import simplemma
from nltk import sent_tokenize,word_tokenize
import numpy as np
import os
import time
import tempfile
nltk.download('punkt')

tmpdir = tempfile.mkdtemp()
mobilenet_save_path = os.path.join(tmpdir, "mobilenet/1/")
dataset = load_dataset("hate_speech_pl")
df =pd.DataFrame(dataset['train'])
hate_s = df[['text']]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Generating train split:   0%|          | 0/13887 [00:00<?, ? examples/s]

Dataset hate_speech_pl downloaded and prepared to /root/.cache/huggingface/datasets/hate_speech_pl/default/1.1.0/40101693880e807040a6b999faa7441cc231e95c81eefa5922ff4a76c8aa48fd. Subsequent calls will reuse this data.


  0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#defining function for remove rt
def remove_angle_brackets(text):
    a=re.compile("<.*?>")
    a=a.sub('',text)
    return a

#applying function to the new column
hate_s['text_no_angle_brackets'] = hate_s['text'].apply(lambda x: remove_angle_brackets(x))
hate_s.text_no_angle_brackets[0]


<ipython-input-3-5359612727c3>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_s['text_no_angle_brackets'] = hate_s['text'].apply(lambda x: remove_angle_brackets(x))


'  Niemiec mówi co innego'

In [ ]:
hate_s['text_lower'] = hate_s['text_no_angle_brackets'].apply(lambda x: x.lower())

<ipython-input-4-7641eda9cf2a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_s['text_lower'] = hate_s['text_no_angle_brackets'].apply(lambda x: x.lower())


In [ ]:
stopwords=adv.stopwords['polish']
#defining the function to remove stopwords from tokenized text
def remove_stopwords(text):
    tokens = word_tokenize(text)
    output= ' '.join([i for i in tokens if i not in stopwords])
    return output


#applying the function
# hate_s['no_stopwords'] = hate_s['text_lower'].apply(lambda x:remove_stopwords(x))

In [ ]:
# TODO
# Czyszczenie danych -> Usunięcie ostrych nawiasów i tego co jest w środku, wieloznaki
# Potencjalnie na przyszłość można spróbować zrobić użytek ze słów które są podkreślone. Jakieś punktowanie słów? 
# Preprocessing -> tokenizacja, lemming, wyliczyć średnią i odchylednie st. znaków dla słów (aby określić wielkość step size'u), wektoryzacja. 
# Zbudować model (sequential + warstwy lstm i dense)


In [ ]:
hate_s['tokens'] = hate_s['text_lower'].apply(lambda x: nltk.word_tokenize(x))


<ipython-input-6-ba58657fd7eb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hate_s['tokens'] = hate_s['text_lower'].apply(lambda x: nltk.word_tokenize(x))


In [ ]:
two_d_text = hate_s['tokens'].values.tolist()
only_text = hate_s['text_lower'].values.tolist()
# two_d_text
one_d_text = []
for _list in two_d_text:
  for element in _list:
    one_d_text.append(element)
one_d_text = ' '.join(one_d_text)
print(one_d_text[:200])

niemiec mówi co innego za każdym razem kiedy wypływa temat homoseksualistów mam mieszane uczucia gt raczej przykład żydowskiego szowinizmu podobno homoseksualiści mają normalny popęd seksualny tylko u


In [ ]:
# hate_s['lemmatized'] = hate_s['text_lower'].apply(lambda x: simplemma.lemmatize(x, lang='pl'))
# hate_s
from collections import Counter
vocab = [key for key , value in Counter(one_d_text).most_common()]
# vocab = [key for key , value in Counter(Boze_niech_to_dziala).most_common()]
print("posortowane od największej frequency", str(vocab))
print(f'{len(vocab)} unique characters')


posortowane od największej frequency [' ', 'a', 'i', 'e', 'o', 'z', 'n', 'w', 's', 'c', 't', 'r', 'y', 'k', 'd', 'm', 'p', 'l', 'j', 'u', 'b', 'g', 'h', 'ł', 'ó', 'ż', 'ą', 'ę', '.', 'ś', ',', 'ć', 'f', 'ń', "'", '1', '0', '-', '!', '9', '\\', '2', '?', '4', 'ź', '3', '5', ')', '(', '8', 'v', ':', '6', '`', '7', 'x', ';', '\xad', '&', '=', '#', '@', '[', ']', '„', '”', '/', '*', '_', '–', 'q', '%', '+', 'ü', '…', 'ö', '~', 'é', '$', '°', 'ä', '»', 'á', '‘', '§', '’', '|', 'ï', '^', '·', 'è', 'ø', 'ß', '“', '{', '—', 'ľ', '«', 'я']
99 unique characters


In [ ]:
import tensorflow as tf
example_texts = ['abcdefg', 'xyz']
# chars = tf.strings.unicode_split(one_d_text[:5000], input_encoding='UTF-8')
chars = tf.strings.unicode_split(one_d_text, input_encoding='UTF-8')
chars

<tf.Tensor: shape=(2527368,), dtype=string, numpy=array([b'n', b'i', b'e', ..., b'.', b'.', b'.'], dtype=object)>

In [ ]:
ids_from_chars = tf.keras.layers.StringLookup(
    vocabulary=list(vocab), mask_token=None)

In [ ]:
ids = ids_from_chars(chars)
ids

<tf.Tensor: shape=(2527368,), dtype=int64, numpy=array([ 7,  3,  4, ..., 29, 29, 29])>

str

In [ ]:
chars_from_ids = tf.keras.layers.StringLookup(
    vocabulary=ids_from_chars.get_vocabulary(), invert=True, mask_token=None)

In [ ]:
chars = chars_from_ids(ids)
chars

<tf.Tensor: shape=(2527368,), dtype=string, numpy=array([b'n', b'i', b'e', ..., b'.', b'.', b'.'], dtype=object)>

In [ ]:
def text_from_ids(ids):
  return tf.strings.reduce_join(chars_from_ids(ids), axis=-1)

In [ ]:
all_ids = ids_from_chars(tf.strings.unicode_split(one_d_text, 'UTF-8'))
all_ids

<tf.Tensor: shape=(2527368,), dtype=int64, numpy=array([ 7,  3,  4, ..., 29, 29, 29])>

In [ ]:
ids_dataset = tf.data.Dataset.from_tensor_slices(all_ids)

In [ ]:
seq_length = 100
sequences = ids_dataset.batch(seq_length+1, drop_remainder=True)

for seq in sequences.take(1):
  print(chars_from_ids(seq))

tf.Tensor(
[b'n' b'i' b'e' b'm' b'i' b'e' b'c' b' ' b'm' b'\xc3\xb3' b'w' b'i' b' '
 b'c' b'o' b' ' b'i' b'n' b'n' b'e' b'g' b'o' b' ' b'z' b'a' b' ' b'k'
 b'a' b'\xc5\xbc' b'd' b'y' b'm' b' ' b'r' b'a' b'z' b'e' b'm' b' ' b'k'
 b'i' b'e' b'd' b'y' b' ' b'w' b'y' b'p' b'\xc5\x82' b'y' b'w' b'a' b' '
 b't' b'e' b'm' b'a' b't' b' ' b'h' b'o' b'm' b'o' b's' b'e' b'k' b's'
 b'u' b'a' b'l' b'i' b's' b't' b'\xc3\xb3' b'w' b' ' b'm' b'a' b'm' b' '
 b'm' b'i' b'e' b's' b'z' b'a' b'n' b'e' b' ' b'u' b'c' b'z' b'u' b'c'
 b'i' b'a' b' ' b'g' b't' b' ' b'r'], shape=(101,), dtype=string)


In [ ]:
for seq in sequences.take(1):
  print(text_from_ids(seq).numpy())

b'niemiec m\xc3\xb3wi co innego za ka\xc5\xbcdym razem kiedy wyp\xc5\x82ywa temat homoseksualist\xc3\xb3w mam mieszane uczucia gt r'


In [ ]:
def split_input_target(sequence):
    input_text = sequence[:seq_length]
    target_text = sequence[1:seq_length+1]
    return input_text, target_text

In [ ]:
split_input_target(list("Tensorflow"))

(['T', 'e', 'n', 's', 'o', 'r', 'f', 'l', 'o', 'w'],
 ['e', 'n', 's', 'o', 'r', 'f', 'l', 'o', 'w'])

In [ ]:
dataset = sequences.map(split_input_target)

In [ ]:
for input_example, target_example in dataset.take(1):
    print("Input :", text_from_ids(input_example).numpy())
    print("Target:", text_from_ids(target_example).numpy())

Input : b'niemiec m\xc3\xb3wi co innego za ka\xc5\xbcdym razem kiedy wyp\xc5\x82ywa temat homoseksualist\xc3\xb3w mam mieszane uczucia gt '
Target: b'iemiec m\xc3\xb3wi co innego za ka\xc5\xbcdym razem kiedy wyp\xc5\x82ywa temat homoseksualist\xc3\xb3w mam mieszane uczucia gt r'


In [ ]:
BATCH_SIZE = 64

BUFFER_SIZE = 10000

dataset = (
    dataset
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))

dataset

<PrefetchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int64, name=None), TensorSpec(shape=(64, 100), dtype=tf.int64, name=None))>

In [ ]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

In [ ]:
class MyModel(tf.keras.Model):
  def __init__(self, vocab_size, embedding_dim, rnn_units):
    super().__init__(self)
    self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
    self.gru = tf.keras.layers.GRU(rnn_units,
                                   return_sequences=True,
                                   return_state=True)
    self.dense = tf.keras.layers.Dense(vocab_size)

  def call(self, inputs, states=None, return_state=False, training=False):
    x = inputs
    x = self.embedding(x, training=training)
    if states is None:
      states = self.gru.get_initial_state(x)
    x, states = self.gru(x, initial_state=states, training=training)
    x = self.dense(x, training=training)

    if return_state:
      return x, states
    else:
      return x

In [ ]:
model = MyModel(
    # Be sure the vocabulary size matches the `StringLookup` layers.
    vocab_size=len(ids_from_chars.get_vocabulary()),
    embedding_dim=embedding_dim,
    rnn_units=rnn_units)

In [ ]:
print(vocab_size)


99


In [ ]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    # print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

In [ ]:
model.summary()

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       multiple                  25600     
                                                                 
 gru (GRU)                   multiple                  3938304   
                                                                 
 dense (Dense)               multiple                  102500    
                                                                 
Total params: 4,066,404
Trainable params: 4,066,404
Non-trainable params: 0
_________________________________________________________________


In [ ]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()

sampled_indices

array([23, 14, 37,  3, 83, 64, 75, 84, 83, 24, 48, 77,  1, 99, 82, 16, 62,
       24, 64, 57, 22, 12, 15,  7, 61, 46, 53, 54, 29, 43, 77, 70, 44, 82,
       70, 43, 45, 23, 64, 94,  7, 14, 77, 71, 33, 63,  4, 72, 61, 97, 42,
       28, 80, 45, 19, 72, 15, 86,  8, 82, 95, 40,  9, 85, 24, 85, 39, 10,
       49, 76, 18, 34, 74, 58, 23, 23, 91, 42, 48, 22, 83, 92, 71, 38, 56,
       10, 12, 81, 57, 14, 63, 62, 85, 26, 89, 66, 87, 11, 22, 58])

In [ ]:
print("Input:\n", text_from_ids(input_example_batch[0]).numpy())
print()
print("Next Char Predictions:\n", text_from_ids(sampled_indices).numpy())

Input:
 b'czyzn\xc4\x85 geje nie gryz\xc4\x85 kiedy kto\xc5\x9b zdaj\xc4\x99 sobie spraw\xc4\x99 jest gejem to ogromny cios nie wiecie jak bardzo'

Next Char Predictions:
 b'hk0i\xc3\xa1]\xe2\x80\xa6\xe2\x80\x98\xc3\xa1\xc5\x82)~ \xd1\x8f\xc2\xbbm@\xc5\x82];grdn#36`.?~\xe2\x80\x934\xc2\xbb\xe2\x80\x93?\xc5\xbah]\xe2\x80\x9cnk~qf[e%#\xc4\xbe2\xc4\x99\xc2\xb0\xc5\xbaj%d\xe2\x80\x99w\xc2\xbb{9s\xc2\xa7\xc5\x82\xc2\xa7!c(\xc3\xb6l\xc5\x84\xc3\xbc\xc2\xadhh\xc3\xa82)g\xc3\xa1\xc3\xb8q-xcr\xc3\xa4;k[@\xc2\xa7\xc5\xbc^\xe2\x80\x9d|tg\xc2\xad'


In [ ]:
loss = tf.losses.SparseCategoricalCrossentropy(from_logits=True)
example_batch_mean_loss = loss(target_example_batch, example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("Mean loss:        ", example_batch_mean_loss)
model.compile(optimizer='adam', loss=loss)
# Directory where the checkpoints will be saved
checkpoint_dir = '/content/drive/MyDrive/Colab Notebooks/training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

Prediction shape:  (64, 100, 100)  # (batch_size, sequence_length, vocab_size)
Mean loss:         tf.Tensor(4.6036243, shape=(), dtype=float32)


In [ ]:
history = model.fit(dataset, epochs=25, callbacks=[checkpoint_callback])

Epoch 1/25
390/390 [==============================] - 30s 63ms/step - loss: 2.4502
Epoch 2/25
390/390 [==============================] - 23s 54ms/step - loss: 1.8155
Epoch 3/25
390/390 [==============================] - 25s 54ms/step - loss: 1.5854
Epoch 4/25
390/390 [==============================] - 26s 62ms/step - loss: 1.4841
Epoch 5/25
390/390 [==============================] - 27s 60ms/step - loss: 1.4176
Epoch 6/25
390/390 [==============================] - 24s 54ms/step - loss: 1.3637
Epoch 7/25
390/390 [==============================] - 24s 57ms/step - loss: 1.3173
Epoch 8/25
390/390 [==============================] - 26s 55ms/step - loss: 1.2728
Epoch 9/25
390/390 [==============================] - 24s 55ms/step - loss: 1.2297
Epoch 10/25
390/390 [==============================] - 23s 55ms/step - loss: 1.1888
Epoch 11/25
390/390 [==============================] - 25s 55ms/step - loss: 1.1485
Epoch 12/25
390/390 [==============================] - 23s 55ms/step - loss: 1.1103
E

In [ ]:
class OneStep(tf.keras.Model):
  def __init__(self, model, chars_from_ids, ids_from_chars, temperature=1.0):
    super().__init__()
    self.temperature = temperature
    self.model = model
    self.chars_from_ids = chars_from_ids
    self.ids_from_chars = ids_from_chars

    # Create a mask to prevent "[UNK]" from being generated.
    skip_ids = self.ids_from_chars(['[UNK]'])[:, None]
    sparse_mask = tf.SparseTensor(
        # Put a -inf at each bad index.
        values=[-float('inf')]*len(skip_ids),
        indices=skip_ids,
        # Match the shape to the vocabulary
        dense_shape=[len(ids_from_chars.get_vocabulary())])
    self.prediction_mask = tf.sparse.to_dense(sparse_mask)

  @tf.function
  def generate_one_step(self, inputs, states=None):
    # Convert strings to token IDs.
    input_chars = tf.strings.unicode_split(inputs, 'UTF-8')
    input_ids = self.ids_from_chars(input_chars).to_tensor()

    # Run the model.
    # predicted_logits.shape is [batch, char, next_char_logits]
    predicted_logits, states = self.model(inputs=input_ids, states=states,
                                          return_state=True)
    # Only use the last prediction.
    predicted_logits = predicted_logits[:, -1, :]
    predicted_logits = predicted_logits/self.temperature
    # Apply the prediction mask: prevent "[UNK]" from being generated.
    predicted_logits = predicted_logits + self.prediction_mask

    # Sample the output logits to generate token IDs.
    predicted_ids = tf.random.categorical(predicted_logits, num_samples=1)
    predicted_ids = tf.squeeze(predicted_ids, axis=-1)

    # Convert from token ids to characters
    predicted_chars = self.chars_from_ids(predicted_ids)

    # Return the characters and model state.
    return predicted_chars, states

In [ ]:
one_step_model = OneStep(model, chars_from_ids, ids_from_chars)

In [ ]:
start = time.time()
states = None
next_char = tf.constant(['PolAIk:'])
result = [next_char]

for n in range(100):
  next_char, states = one_step_model.generate_one_step(next_char, states=states)
  result.append(next_char)

result = tf.strings.join(result)
end = time.time()
print(result[0].numpy().decode('utf-8').upper(), '\n\n' + '_'*80)
print('\nRun time:', end - start)

POLAIK: LEGALIZACYJNI I CHCEMY ZNICZE NIE BĘDZIE W MOCZACH JEST BARDZO WOLILIŚMY TAKI OBSERWATOR BON INW ID 

________________________________________________________________________________

Run time: 0.2692103385925293


In [ ]:
tf.saved_model.save(one_step_model, '/content/drive/MyDrive/Colab Notebooks/one_step')


INFO:tensorflow:Assets written to: /content/drive/MyDrive/Colab Notebooks/one_step/assets


In [ ]:
import tensorflow as tf
import re
import pandas as pd
from datasets import load_dataset
import pandas as pd
import advertools as adv
import nltk
import simplemma
from nltk import sent_tokenize,word_tokenize
import numpy as np
import os
import time
PolAIk_model = tf.saved_model.load('/content/drive/MyDrive/Colab Notebooks/one_step')
PolAIk_model

<tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject at 0x7f3c0d935ac0>

In [ ]:
start = time.time()
states = None
next_char = tf.constant(['PolAIk:'])
result = [next_char]

for n in range(100):
  next_char, states = PolAIk_model.generate_one_step(next_char, states=states)
  result.append(next_char)

result = tf.strings.join(result)
end = time.time()
print(result[0].numpy().decode('utf-8').upper(), '\n\n' + '_'*80)
print('\nRun time:', end - start)

POLAIK: LECZ CAŁA LIST DO KWAŚNIEWSTWO TOLERUJE ZABIJAMY W PAŃSTWIE ALBO NAGRANIJ BYŁ UKRYWANIE IM SIĘ ZNAL 

________________________________________________________________________________

Run time: 0.26991772651672363
